### ISSUE TITLE
Preisvorschlag inkorrekt

### ISSUE THREAD

**Issue by insilentio** [thomashartmeier/dorfbraeu-admin#1]
Die Berechnung des Preisvorschlags macht keinen (nachvollziehbaren) Sinn. Sollte von Anz. Flaschen und Harassen abhängig sein. Es fragt sich, ob das Feld überhaupt editierbar sein muss.
![image](https://github.com/user-attachments/assets/dc6c3ea5-0eb2-46c3-8bf7-09bf75ffb75e)

**Comment by thomashartmeier** [comment]
Genau, das muss ich noch machen (stimmt, hab ich vergessen zu erwähnen im Mail an dich). Momentan ist es einfach random number, die dort jeweils angezeigt wird 😊

**Comment by thomashartmeier** [comment]
Yay to 0cda4212!

Die Berechnung des Preises ist nun sauber abhängig von: Anzahl Bierflaschen, Anzahl Harasse, Wahl ob Geschenk oder nicht, Wahl des Kunden (Wiederverkäuferpreis oder nicht).

✅
