### ISSUE TITLE
Company Feld in clients zu kurz

### ISSUE THREAD

**Issue by insilentio** [thomashartmeier/dorfbraeu-admin#10]
company scheint ein varchar(20) zu sein, das ist zu kurz. Reicht z.B. nicht für "Restaurant Grundstein"

**Comment by thomashartmeier** [comment]
Danke fürs Finden! Hab `company` jetzt auf `varchar(50)` geändert und beim `Restaurant Grundstein` Eintrag das fehlende `n` ergänzt 😉
