### ISSUE TITLE
Rabatt ergänzen

### ISSUE THREAD

**Issue by insilentio** [thomashartmeier/dorfbraeu-admin#2]
Die `orders`-Tabelle benötigt noch ein Rabattfeld für die korrekte Preisberechnung.

Evt. auch schon bei clients ein Rabattfeld ergänzen; das könnte dann als Default bei den Bestellungen schon als Vorschlagswert übernommen werden.

**Comment by thomashartmeier** [comment]
Hmm. Meine Idee war es, dass wir bei den Clients ja den Tag "Wiederverkäufer" haben und damit können wir dann den Preis berechnen. Ich wollte dann aber diesen Preis nicht fix machen, da es ja bestimmt hin&da aus verschiedensten Gründen Abweichungen gibt. Deshalb war meine Idee den berechneten Preis einfach so als Hilfe anzuzeigen und dann kann man den übernehmen oder allenfalls anpassen.

**Comment by insilentio** [comment]
let's discuss...

**Comment by insilentio** [comment]
*Entscheid*
Rabattfeld braucht es nicht, da wir den Jahresrabatt erst per Ende Jahr berechnen werden und für eine neue Bestellung anrechnen.
