### ISSUE TITLE
Amount Feld in orderItems

### ISSUE THREAD

**Issue by insilentio** [thomashartmeier/dorfbraeu-admin#3]

**Comment by insilentio** [comment]
Ich nehme an, das Feld ist für die Menge (Anz. Flaschen, Anz. Harasse) gedacht. Dann würde ich das der Klarheit lieber `quantity` nennen.

**Comment by thomashartmeier** [comment]
Ja genau. Stimmt, guter Punkt, kann ich ändern um es klarer zu machen 👍🏼

**Comment by thomashartmeier** [comment]
Gemacht mit f9393d8b.
