### ISSUE TITLE
containers Tabelle

### ISSUE THREAD

**Issue by insilentio** [thomashartmeier/dorfbraeu-admin#4]
Wofür ist die Tabelle? Was sind Container?

**Comment by thomashartmeier** [comment]
Das war schon etwas "forward-looking" diese Tabelle: Die Einträge in dieser Tabelle z.z. sind Flaschen oder Kegs. Es ist somit schon alles ready für später, wenn wir dann (vielleicht) einmal auch Kegs verkaufen 😊
