### ISSUE TITLE
clients Tabelle

### ISSUE THREAD

**Issue by insilentio** [thomashartmeier/dorfbraeu-admin#5]
Die Felder `email` und `phone` akzeptieren Nonsens-Einträge, würde sich wohl lohnen, da auf gewisse Formate zu prüfen.

**Comment by thomashartmeier** [comment]
Ja, hab ich mir vorerst mal erlaubt, das einfach zu halten. Aber ist ein guter Erweiterungspunkt. Zum Glück machen ja nur wir 4 die Einträge und nicht Hinz&Kunz. Da muss man nicht so ausgiebig die Eingaben checken... vielleicht... 😉

**Comment by insilentio** [comment]
yep, das ist mehr so für die Erweiterung für die fernere Zukunft 😆

**Comment by thomashartmeier** [comment]
Gemacht mit ef0043d1.
