### ISSUE TITLE
Kunden: Muss-Felder

### ISSUE THREAD

**Issue by insilentio** [thomashartmeier/dorfbraeu-admin#7]
Ich glaube, bei den Kunden sollte als Minimalbedingung ein Name (Vor- oder Nachname) vorliegen. Es macht keinen Sinn, nur per eMail/Telefon mit Leuten zu kommunizieren, wenn man den Namen nicht kennt.
Im Moment kann man sogar nur eine Adresse erfassen, das empfinde ich als falsch.

**Comment by thomashartmeier** [comment]
Ja, ich hab zuerst gedacht, ich erlaube das Erfassen einer Bestellung mit nur E-mail, oder nur Tel etc. und dass man den Rest dann später nachtragen kann. Aber ich glaube du hast Recht, Minimum Vor- oder Nachname sollte schon auch noch rein. Kann ich machen 👍🏼

**Comment by thomashartmeier** [comment]
Gemacht mit 3a2aed1e 👍🏼

**Comment by insilentio** [comment]
Hübsche Fallunterscheidung 😝
