### ISSUE TITLE
clients Tabelle

### ISSUE THREAD

**Issue by insilentio** [thomashartmeier/dorfbraeu-admin#8]
Die `clients` sollten mehrere Adressen (Rechnungsadresse, Lieferadresse, ...) erlauben. Evt. auch mehrere Telefonnummern und eMail Adressen.

Würde das  aber in die bestehende `clients` Tabelle als zusätzliche Felder aufnehmen (keine separate Adress-Tabelle führen).

**Comment by thomashartmeier** [comment]
Ok, guter Punkt 👍🏼  Kann ich machen.

**Comment by insilentio** [comment]
plus ein Feld "Firmenname"

**Comment by thomashartmeier** [comment]
Neues Feld Rechnungsadresse: 786dff65.

**Comment by thomashartmeier** [comment]
Neues Feld Firma: d43cd5e4.
