### ISSUE TITLE
Berechtigung zum Editieren

### ISSUE THREAD

**Issue by insilentio** [thomashartmeier/dorfbraeu-admin#9]
ich verstehe zwar die Grundidee von
_`Bestellungen können nur von der Person editiert werden, die die entsprechende Bestellung erstellt hat.`_

Aber das ist problematisch, weil bei Zahlungen auf Rechnung nicht die erfassende Person editieren muss, sondern die Buchhaltung. Wenn ich das jedem von Euch melden muss, dass Ihr das selbst updatet, ist das ziemlich ineffizient.

**Comment by thomashartmeier** [comment]
Guter Punkt. Genau das ist mir auch bereits durch den Kopf! Gefixt mit 6d58fcc2. ✅
